### ISSUE TITLE
Broken timer when BPM is not 120

### ISSUE THREAD

**Issue by NutchapolSal** [chrislo27/RhythmHeavenRemixEditor#216]
### Information
**Log file**: I don't think it needs a log file

**Editor version**: 3.5.1

### Description
The timer doesn't count correctly when the BPM is set before beat 0 and not 120

### Behaviours
**Expected behavior**: Normal time

**Actual behavior**:  It doesn't get to 00:00.000 at beat 0, and.. I don't know how to explain that another behavior
![image](https://user-images.githubusercontent.com/17706539/33244933-31c77cd6-d333-11e7-8f5c-c8b5634881a6.png)
![image](https://user-images.githubusercontent.com/17706539/33244960-c1b6d7f6-d333-11e7-8671-d81b0426f8f6.png)
(what happened at 162bpm)

**Comment by chrislo27** [comment]
If you don't think it needs a log file, then I don't think I need to review this. Provide one or I will close this issue.

**Comment by chrislo27** [comment]
While the negative sign on the seconds indicator has been fixed, the behaviour you are attempting to describe is correct. If one places a tempo change for 240 BPM at beat -1, starting from beat -1 is 240 BPM and thus the seconds difference will change.

**Comment by NutchapolSal** [comment]
I think you didn't understand the issue here
![untitled-1](https://user-images.githubusercontent.com/17706539/33264604-da5d3ed6-d3a0-11e7-835e-b521ff2b4172.png)
(green = reality, red = expected)
The issue is that the negative time the program calculated only works on 120 bpm and not on any other tempo
At -16 beats 120 bpm, It takes 8 seconds to reach beat 0 but on 240 and 60 bpm it takes 4 seconds and 16 seconds respectively, The program still uses -8 seconds anyways and that caused the beat 0 to not be on 0:00

And here is a log file that you want
[log_2017-11-27_18-05-19.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1505669/log_2017-11-27_18-05-19.txt)

**Comment by chrislo27** [comment]
This is intentional. Tempo changes only affect the tempo starting AFTER their mark (that is, excluding the beat they are on and affecting it towards positive infinity). Because they rely on the "previous" or default tempo, all tempo changes (that are first) at beat -16 will always start at -8 seconds. Calculation-wise, time flows forward. Negative distance is a side-effect of negative time which will seem odd at first but calculation-wise it works. 

While I understand that you may think that beat 0 *should* seem like seconds 0, this only works when time is a positive real number. Time flows from negative infinity to positive infinity rather than stemming out from zero like a number line does.

Thank you for the diagram. I hope this clears things up.
