### ISSUE TITLE
Music selector won't open in fullscreen

### ISSUE THREAD

**Issue by thatactualdude** [chrislo27/RhythmHeavenRemixEditor#225]
### Information
**Log file**: 
[log_2018-01-04_14-41-29.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1604946/log_2018-01-04_14-41-29.txt)

**Editor version**: 3.6.5

### Description
I'm still trying to open the music selectors (plus save and load) and I'm still reproducing the same issue over and over.
### Behaviours
**Expected behaviour**: Each selector comes up as usual.

**Actual behaviour**: I was stuck on every screen (when trying to open) no matter what I did.

**Comment by chrislo27** [comment]
From the little information you have given me, I can say that you need to close the chooser before you can advance. You have not specified if the chooser *even appears*.

However, since this is a continuation of a prior issue that still has no reproducible test case, I will leave this issue open.

I have prepared a test application for you. You need to open Terminal in the directory with the files (after unzipping the archive), run `java -Dprism.verbose=true -Dprism.debug=true ChooserTest`. Click the button and see if a save dialog appears (it only prints to the console). You should select a file, and click Select/Save, and do the same thing but click Cancel. Report back with the full terminal logs up to the shutdown point.

[JavaFX File Chooser Test.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1605021/JavaFX.File.Chooser.Test.zip)

**Comment by thatactualdude** [comment]
[log.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1605568/log.txt)

**Comment by chrislo27** [comment]
I can see that it worked. I will investigate further and may give you further tests that mimic RHRE3's choosers.

**Comment by chrislo27** [comment]
Here is a test version of RHRE3 v3.6.5 just for you. There are slight tweaks to every file chooser. Please also use the terminal command `java -Dprism.verbose=true -Dprism.debug=true -jar RHRE3.jar` (again, after extracting the jar file). Please let me know if the choosers open, and attach a log file of the terminal output.

[RHRE3-javafx-fix-test1.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1605594/RHRE3-javafx-fix-test1.zip)

**Comment by thatactualdude** [comment]
I could not open the jar file in Terminal a second time, so I don't have logs for the save/load.
[musiclog.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1607653/musiclog.txt)

I also took a screenshot of the selector:
![screen shot 2018-01-05 at 11 14 56 am](https://user-images.githubusercontent.com/34498702/34624516-76eb9c2a-f20a-11e7-8df1-a33725237d74.png)

**Comment by chrislo27** [comment]
You have not stated if the choosers open or not, like I requested.

I notice that you put the editor into fullscreen. Due to my lack of logging (which I have just fixed!) I don't state when screen changes occur.

Do you put the editor into fullscreen **before** or **after** going into Music Select?

**Comment by thatactualdude** [comment]
As soon as I launched the editor, it went into fullscreen.

**Comment by chrislo27** [comment]
Have you tried running these tests in windowed mode? If it is a fullscreen problem, I would like to absolutely ensure that.

**Comment by thatactualdude** [comment]
The selectors open in windowed, but this happens with the screen:
![screen shot 2018-01-05 at 11 36 42 am](https://user-images.githubusercontent.com/34498702/34625221-ba1bfb0a-f20c-11e7-90c0-0ca24ecb3280.png)

**Comment by chrislo27** [comment]
Have the selectors *always* worked in windowed mode?

**Comment by thatactualdude** [comment]
Yes, they have.

**Comment by chrislo27** [comment]
So, this issue only occurs in fullscreen. Why you neglected to state that for weeks is beyond me, but at least I can begin to address the issue knowing where the situation is.

If you Cmd+Tab out of RHRE3, are the file selectors present? I know that on Windows (7) the application actually hides itself (and exits fullscreen temporarily) to show the dialogs.

**Comment by thatactualdude** [comment]
While on fullscreen, it wouldn't even let me cmd+tab out of the editor.

**Comment by chrislo27** [comment]
Can you verify that this setting is **checked**: System Preference > Mission Control > "When switching to an application, switch to a space"

Apparently this is a very macOS specific thing where fullscreen apps get their own "screen" (not sure of exact terminology) and Cmd+Tab does not show them in the switcher. Instead, you have to switch desktops/screens in order to navigate through other applications.

**Comment by thatactualdude** [comment]
![screen shot 2018-01-05 at 11 52 52 am](https://user-images.githubusercontent.com/34498702/34625814-fe337c26-f20e-11e7-90c1-795c0476ba75.png)

**Comment by chrislo27** [comment]
This is the support article for space switching: https://support.apple.com/kb/PH25574?locale=en_US

Supposedly Ctrl+Left and Ctrl+Right switch between spaces. Have you tested this?

**Comment by thatactualdude** [comment]
I'm doing both, but it's just sliding through the beats.

**Comment by chrislo27** [comment]
Try Cmd+H (apparently this is hide program). If this doesn't work, I strongly suggest you do not use fullscreen. I am not sure of the oversized program in windowed mode (you haven't said anything related to that), but I believe leaving it in windowed mode works.

This is looking more and more like a Mac problem than it is anything else. If you're on a laptop, supposedly there are other swipe gestures you can do to bring up menus and whatnot, but I don't know the specifics.

**Comment by thatactualdude** [comment]
(The oversized program in windowed mode happened, forgot to tell you that)
Cmd+H just makes a black screen.

**Comment by chrislo27** [comment]
I'm going to rule this as a Mac context issue with fullscreen.

I would like to address the oversized window problem though (I suspect it's an issue with HDPI, again). If you'd like, you can provide steps to reproduce the issue consistently here, or make a new issue. (I recommend the latter.)
