### ISSUE TITLE
Hole In One doesn't have a copy under "Megamix" games section

### ISSUE THREAD

**Issue by GreenGhost21** [chrislo27/RhythmHeavenRemixEditor#270]
## Description of problem
No Hole In One under the Megamix tab

## Description of solution
Add it to the games listed under the tab

## Description of alternatives
Don't think it needs one? Seems like an oversight more than anything else.

## Additional context
No context needed, assuming my copy is like everyone else's.

**Comment by GreenGhost21** [comment]
Apologies for the lack of detail. Additional apologies if I used the wrong template for this.

**Comment by chrislo27** [comment]
Thanks for your concern.

The Hole in One SFX for Megamix are identical to the ones in Fever. Since we only make "series"-separate games if the SFX do differ (a good example is Fillbots in DS and Megamix where in the latter case they have a shortened "OK" sound), Hole in One will remain in the Fever section since that is its original game.

However, if you do feel that there is a major difference between sounds in the Hole in One versions, we may try to get the SFX split. Keep in mind that SFX extraction from Megamix is very difficult, though.

(And your issue is well-formatted, so don't worry about that.)
