### ISSUE TITLE
I'm not able to open the editor, sadly...

### ISSUE THREAD

**Issue by tucq27** [chrislo27/RhythmHeavenRemixEditor#305]
### Information
**Log file**: 
![Log](https://user-images.githubusercontent.com/58394986/70658725-4d149a00-1c3d-11ea-9927-a37d8b9ef90c.PNG)

**Editor version**: v3.18.8

### Description
Not much to say here, I tried to open the program and... Well, no success, as you may have guessed! I don't really have much more information aside from that, sorry...
(Also, yeah, I have Java...)
### Behaviours
**Expected behaviour**: Well, the editor was _supposed_ to open...

**Actual behaviour**: It didn't. And, y'know, showed the log linked to this issue...

## Steps to reproduce issue
1. Open the "run_portable_windows.bat" file;
2. Realize I've done something wrong;
3. ...And that's about it!
4. ...
5. Have a nice day! I appreciate your work!

**Comment by chrislo27** [comment]
Hi there,
Thank you for your report.

Please upload the log file associated with this run, you can find them in the directory located at `C:\Users\User\.rhre3\logs`.

Thanks.

**Comment by lightninghawk957** [comment]
hate to ask, but do you think you could make a little tutorial?

**Comment by tucq27** [comment]
Sorry for taking too long to answer, but... Said folder isn't in the directory you presented me, which is probably a weird or rare case... Anyway, here's a screenshot, just to prove my point:
![Screenshot](https://user-images.githubusercontent.com/58394986/71493266-28fbb000-281c-11ea-99ac-f76873b66d11.PNG)
(Also, something I forgot to mention, is that I was never able to open the editor at all, which is probably the sole reason why the folder isn't there in the first place...)
Have a nice day, and Merry Christmas!

**Comment by chrislo27** [comment]
First, [a new, large update for RHRE](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.19.0) was released after this report was made. Please download and test that version, both in **non-portable** and **portable mode**. If the problem does not happen in either modes, then we can mark this issue as resolved.

For portable mode log files, please check `C:/Users/User/Documents/tucq!/Remix editor/Rhythm Heaven Remix Editor` for the `.rhre3` folder, since the `.rhre3` folder generates alongside the jar file in portable mode. You may have to enable viewing of hidden files and folders in File Explorer.

**Comment by chrislo27** [comment]
Closed due to inactivity.
