### ISSUE TITLE
Versions 3.20.0 and later refuse to start on macOS Catalina

### ISSUE THREAD

**Issue by Alchemy-king** [chrislo27/RhythmHeavenRemixEditor#323]
### Information
Log file: Unfortunately, I could not find it no matter how hard I tried. It seems that it's in a place so obscure I can't find it.

Version: 3.20.0

### Description
Exactly what it sounds like. Trying to open the .jar file gives the message "The Java JAR file "RHRE.jar" could not be launched. Check the Console for possible error messages." I have checked the Console time and time again, and nothing has come up. In case you're wondering, the .command file doesn't work either. It gives this: 

"Last login: Thu Jun 11 15:08:15 on ttys001
/Users/(me)/Downloads/Rhythm\ Heaven\ Remix\ Editor\ 3/run_macOS.command ; exit;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(my)-MacBook-Air:~ (me)$ /Users/(me)/Downloads/Rhythm\ Heaven\ Remix\ Editor\ 3/run_macOS.command ; exit;
-bash: /Users/(me)/Downloads/Rhythm Heaven Remix Editor 3/run_macOS.command: /bin/bash^M: bad interpreter: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

### Behaviours
**Expected behaviour**: Version 3.20.0 would run with little issue.

**Actual behaviour**: Version 3.20.0 refused to start, no matter how hard I tried.

## Steps to reproduce issue
1. Simply try to open either the .jar or the .command file on MacOS Catalina.

I'm sorry this is so vague, but any possible holders of more information are either nearly impossible to find or so vague that they tell me nothing.

**Comment by chrislo27** [comment]
Next time, please upload the log file. On macOS it is found in the directory `<your user home>/.rhre3/logs`. Enable viewing of hidden files/folders if you have to.

This issue has been resolved for v3.20.2/v3.21.0 since macOS Catalina no longer comes with the bash shell.

In the meantime you may use this .command file (unzip the zip file) or downgrade your OS version.

[new_command.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4768188/new_command.zip)
