### ISSUE TITLE
Uh oh

### ISSUE THREAD

**Issue by randomgithuboofcom** [chrislo27/RhythmHeavenRemixEditor#336]
### Information
**Log file**: [Upload your appropriate log file (found in `\<user>/.rhre3/logs`) here, it contains system information and other important info to help debug the problem]()

**Editor version**: v3.20.3

### Description
RHRE keeps on failing to load, several times later, it crashed!

### Behaviours
**Expected behaviour**: It... was going to work.

**Actual behaviour**: RHRE crashed

## Steps to reproduce issue
1. Step one
2. Step two
3. etc.

**Comment by chrislo27** [comment]
Hi, please upload your log file, as it is required. You can find it at `C:/Users/<your user name>/.rhre3/logs`, they are timestamped. If you cannot see the .rhre3 folder, [enable viewing of hidden files and folders](https://support.microsoft.com/en-ca/help/14201/windows-show-hidden-files).

Please make a best attempt to fill out the issue template correctly. I know for fact there is no "RHRE.exe" and the expected behaviour of "starting to work on a custom minigame" is not helpful.

**Comment by randomgithuboofcom** [comment]
I don't see my log file

**Comment by chrislo27** [comment]
Closed due to insufficient info.
