### ISSUE TITLE
Is this thing on?

### ISSUE THREAD

**Issue by KGirl-Kreator22** [chrislo27/RhythmHeavenRemixEditor#338]
### Information
**Log file**: [Upload your appropriate log file (found in `\<user>/.rhre3/logs`) here, it contains system information and other important info to help debug the problem]()

**Editor version**: v3.20.3

### Description
The game crashes whenever I try to add the pose for the fans on my remix. It makes me want to start all over.

### Behaviours
**Expected behaviour**:  My mind keeps telling the program not to crash!

**Actual behaviour**: Crashed. 

## Steps to reproduce issue
1. Step one
2. Step two
3. etc.

**Comment by chrislo27** [comment]
Hi, please upload your log file, as it is required. You can find it at `C:/Users/<your user name>/.rhre3/logs`, they are timestamped. If you cannot see the .rhre3 folder, [enable viewing of hidden files and folders](https://support.microsoft.com/en-ca/help/14201/windows-show-hidden-files).

Please make a best attempt to fill out the issue template correctly. Expected behaviour is not whatever your "mind" wants it to be, but a detailed of what you were doing, what happened instead, and what you thought would've happened.

**Comment by Dylstructor** [comment]
Hey! I am not able to reproduce this bug. But as @chrislo27 said above, please upload your logs

**Comment by KGirl-Kreator22** [comment]
My log was submitted. Thank you.

**Comment by chrislo27** [comment]
Closed due to insufficient information.
