### ISSUE TITLE
Program won't load and keeps crashing on startup

### ISSUE THREAD

**Issue by FruitsPunchParfaits34** [chrislo27/RhythmHeavenRemixEditor#341]
### Information
**Log file**: 
[hs_err_pid21083.log](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/5292208/hs_err_pid21083.log)

**Editor version**: v3.20.4

### Description
The editor won't open and crashes upon startup.

### Behaviours
**Expected behaviour**: To open the program.

**Actual behaviour**: Would not load the program and crashes immediately.

## Steps to reproduce issue
1. Download recent file
2. Attempt to open program
3. No step 3

**Comment by chrislo27** [comment]
Hi, [as of 2020-08-14, macOS is not a supported OS for RHRE](https://github.com/chrislo27/RhythmHeavenRemixEditor#requirements) so I cannot help you with your issue.

**Comment by FruitsPunchParfaits34** [comment]
Hi, just wanted to ask why Mac versions isn't being supported anymore if as a result of extreme technical issues or the something similar and if there is another alternative solution towards being able to access the program again. Thanks

**Comment by chrislo27** [comment]
macOS support was dropped for a number of technical reasons, including and not limited to:
* OpenGL support being dropped as of 10.14 Mojave
* Bash support being dropped as of 10.15 Catalina
* Unsigned application support being dropped as of 10.15 Catalina, forcing developers to buy an annual [Apple developers license](https://developer.apple.com/programs/enroll/) along with Apple computing hardware

Other relevant stats and info:
* macOS users make up less than 1% of active users, even with the 5x surge in new users since last July
* macOS users have reported the most OS-specific problems prior to support being dropped
* macOS users have had the least feature parity, notably time stretching not being supported

Unfortunately, there is no incentive, financial, motivational, or otherwise, for me to support macOS currently. The alternative is to run on a Windows or Linux operating system. Thank you for your understanding.
