### ISSUE TITLE
Seriously will not open.

### ISSUE THREAD

**Issue by Somebodyherelguess** [chrislo27/RhythmHeavenRemixEditor#347]
I have all the requirements
Did everything I was told to do
Stayed up all night trying to open it
Nothing about it on the internet
No reason to use the template because everything would be put in the What really happened section

**Comment by chrislo27** [comment]
Please do not repeatedly make issues for non-bugs. GitHub Issues is for bug reports. [Please do not also make alternate accounts](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-terms-of-service#3-account-requirements) when you have just made issue #346.

Again, I will ask you ensure you have all the [requirements](https://github.com/chrislo27/RhythmHeavenRemixEditor#requirements) and that you follow the [installation steps](https://github.com/chrislo27/RhythmHeavenRemixEditor#installation). For example, are you sure you have Java installed? https://java.com/en/download/manual.jsp Otherwise you will run into the same error as before ("'java' is not recognized as an internal or external command, operable program or batch file.").

Creating an issue with no supporting evidence is a waste of maintainers' time, so please provide as much information as possible to make it as easy as possible.

**Comment by Somebodyherelguess** [comment]
If you're going to be so ignorant to everything, there's no reason for me to even try to get help.
